name: main

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
  third:
    needs: first
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
  fourth:
    if: always() # run this job even if one of its dependent job fails
    needs: [second, third]
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
